### ISSUE TITLE
ron.prob needed or not?

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-ron#2]
https://github.com/apertium/apertium-ron/commit/352f44b5abd002eca10aaecbcf9ade85d62b4775 removed ron.prob from files to be installed, but https://github.com/apertium/apertium-ron-cat currently needs it. Either ron.prob should be installed, or ron-cat should be fixed to not need it.

@MarcRiera

**Comment by marcriera** [comment]
Thanks, it was removed by mistake and it is definitely needed by the tagger. It now installs correctly.
